### PR TITLE
Add i os metal support

### PR DESCRIPTION
**Pull request by PhilMoe**
I added the new ios metal target and here it runs fine in the simulator (right after a build from ted) and on my iPhone (building from xcode). Please have a look and try if it works on your devices as well.

### CODE REVIEW

**Comment by MikeHart66** [comment]
Questions: Did you manually added the framework to the file targets/ios_metal/template/CerberusGame.xcodeproj/project.pbxproj ?

**Comment by PhilMoe** [comment]
@MikeHart66 I don't really know if this is manually, but here is what I did: 
After the build I opened the project in xcode and added the framework to be embedded. Then I copied the modified pbxproj file to replace the target template file. After that I looked at the changed lines in github desktop and discarded all the changes that seemed not to be related to the framework. 
After looking at the changes again I saw that there is one line changing the dev team and I am not quite sure how it got in there. Does is work on your machine?

**Comment by MikeHart66** [comment]
I didn't test it so far, will do whne I find time. I just saw that the hash ids inside the file looked the same and was wondering. Simple question. Sounds like there is no problem which could arise when entries are added manually instead through xcode, like you have done.

**Review by MikeHart66 — APPROVED** [review]
Good job. It works on my Mac Mini M2 in the Xcode Simulator and on my IPhone 11

**Pull request merged**
