### PR TITLE
Fix glfw high dpi retina

### PR DESCRIPTION
**Pull request by PhilMoe**
I introduced a config constant #GLFW_HIGH_DPI_ENABLED to make the usage of the whole resolution possible (=1) while keeping old fashioned apps running as usual (=0), which is the default setting so far. 

I guess this fix is not ready for merging as I expect some issues with other targets than glfw and there might be problems when using stuff like setviewport or setscissors and getting the values later.
But for testing it should be fine.

### CODE REVIEW

**Review by MikeHart66 — CHANGES_REQUESTED** [review]
I testet this with the current examples. 

`#GLFW_HIGH_DPI_ENABLED=1
#GLFW_WINDOW_RESIZABLE=True`
As soon as you make windows resizable and activate the highDPI feature on a non DPI system, they behave not right. Maximize the window and go back.

Text is drawn either to small or to big and Scissors are off when mazimised and after going back.

**Comment by MikeHart66** [comment]
Imho

`#GLFW_HIGH_DPI_ENABLED=1`

should be default on the GLFW target as there you can't determine at compile time, if an app will run on a retina display or not.

**Comment by PhilMoe** [comment]
> 
> 
> Imho
> 
> `#GLFW_HIGH_DPI_ENABLED=1`
> 
> should be default on the GLFW target as there you can't determine at compile time, if an app will run on a retina display or not.

Maybe the name is misleading. It just says you can't access the true resolution of the highDPI display and all content will be scaled up to fill the window on a highDPI display.

**Comment by MikeHart66** [comment]
> > Imho
> > `#GLFW_HIGH_DPI_ENABLED=1`
> > should be default on the GLFW target as there you can't determine at compile time, if an app will run on a retina display or not.
> 
> Maybe the name is misleading. It just means you can't access the true resolution of the highDPI display and all content will be scaled up to fill the window on a highDPI display.

Ah ok. Then it makes sense.

**Comment by MikeHart66** [comment]
Seems to work fine, so I will merge this.

**Pull request merged**
